"""Generate the hidden team-lookup page for the course website from team_ids.csv.

The site and its repo are public, so the page stores only salted SHA-256 hashes
of UCIDs, never the IDs themselves; the browser hashes what the student types.

Usage: python3 make_lookup_page.py [output path]
"""
import csv
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else \
    Path.home() / "Web/cs-490-website/team-lookup.md"
SALT = "TODO" # set this to something unique each semester


def h(ucid):
    return hashlib.sha256((SALT + ucid.strip().lower()).encode()).hexdigest()[:20]


with open(HERE / "team_ids.csv", newline="") as f:
    table = {h(r["Student ID"]): r["Team"] for r in csv.DictReader(f)}

PAGE = """---
layout: page
title: Team Lookup
permalink: /team-lookup/
nav_exclude: true
search_exclude: true
---

<!-- Generated by teaching/490/au26/teams/make_lookup_page.py from team_ids.csv. Do not edit by hand. -->

# Find Your Project Team
{: .no_toc }

Enter your UCID (the part of your NJIT email before the `@`) to see which project team you are on.

{% raw %}
<form id="team-form" autocomplete="off" style="margin: 1.5rem 0;">
  <label for="ucid" style="display:block; font-weight:600; margin-bottom:.4rem;">UCID</label>
  <input id="ucid" name="ucid" type="text" inputmode="email" autocapitalize="none" spellcheck="false"
         placeholder="e.g. abc123" required
         style="font-size:1.2rem; padding:.5rem .7rem; width:100%; max-width:20rem; box-sizing:border-box; border:1px solid #bbb; border-radius:4px;">
  <button type="submit" class="btn btn-primary" style="margin-top:.8rem; font-size:1.1rem;">Look up my team</button>
</form>
<div id="team-result" aria-live="polite" style="font-size:1.4rem; min-height:2em;"></div>
<script>
(function () {
  var SALT = __SALT__;
  var TEAMS = __TABLE__;
  var form = document.getElementById("team-form");
  var input = document.getElementById("ucid");
  var out = document.getElementById("team-result");
  function hex(buf) {
    return Array.prototype.map.call(new Uint8Array(buf), function (b) {
      return ("0" + b.toString(16)).slice(-2);
    }).join("");
  }
  form.addEventListener("submit", function (e) {
    e.preventDefault();
    var ucid = input.value.trim().toLowerCase().replace(/@.*$/, "");
    if (!ucid) { return; }
    crypto.subtle.digest("SHA-256", new TextEncoder().encode(SALT + ucid)).then(function (buf) {
      var team = TEAMS[hex(buf).slice(0, 20)];
      out.textContent = "";
      if (team) {
        var strong = document.createElement("strong");
        strong.textContent = "Team " + team;
        out.appendChild(document.createTextNode(ucid + ": you are on "));
        out.appendChild(strong);
      } else {
        out.textContent = "No team found for \\u201c" + ucid + "\\u201d. Check the spelling, or ask a member of course staff.";
      }
    });
  });
})();
</script>
{% endraw %}
"""

page = PAGE.replace("__SALT__", json.dumps(SALT)).replace(
    "__TABLE__", json.dumps(table, separators=(",", ":")))
OUT.write_text(page)
print(f"wrote {OUT} with {len(table)} entries")
